### PR TITLE
add testing for user and password

### PR DESCRIPTION
**Pull request by ottobackwards**
@willbuck 
I have put the passwords in the tests.  Check this out and see if it is hitting your code

---
This change is [Reviewable](https://reviewable.io/reviews/willbuck/commons-vfs/1)

### CODE REVIEW

**Comment by willbuck** [comment]
It doesn't look like it does. I ran `mvn verify` via IntelliJ with breakpoints set inside `SftpClientFactory.createProxySOCKS5` and `SftpClientFactory.createProxyHTTP`, and neither were hit. I'm actually not able to hit any breakpoints though, so I'm not confident what's actually getting hit and what isn't. I don't have a lot of experience running Maven projects, most of my work is with gradle.

**Comment by willbuck** [comment]
Okay, I was finally able to get some breakpoints hit, but still not in the new functions we care about. So I don't think these changes help with testing the new functionality, unfortunately. @ottobackwards Can you verify that you are seeing the same thing?

**Comment by ottobackwards** [comment]
This is with my PR:
screen shot 2018-05-01 at 16 39 00
screen shot 2018-05-01 at 16 38 55

So it looks like the password is not being parsed correctly?
I can debug in intellij

**Comment by willbuck** [comment]
@ottobackwards it looks like that breakpoint you set is in `SftpClientFactory.createStreamProxy`: that isn't the method I edited for the PR, right?

**Comment by ottobackwards** [comment]
screen shot 2018-05-01 at 16 47 00

The second set password is wrong

**Comment by ottobackwards** [comment]
Ok, check out my latest.
I have not taken your last change @willbuck

**Comment by ottobackwards** [comment]
Yes it is that method, but I don't have your tests.   I'm just showing that the test code is passing in the proxy user/pass correctly.

**Comment by ottobackwards** [comment]
OK, the issue is that we need a *real* proxy server for these tests to work, I think

**Comment by willbuck** [comment]
Yes, sorry for the radio silence yesterday I was working on deploying a patch to my client's internal artifcatory, to unblock some of their work.

Agreed that the thing I'm struggling with is either finding a *real* **authenticated** HTTP/SOCKS5 proxied SFTP server to write a test against (that we can store the credentials to in the test safely), or how to mock one within the testing framework in the repo. That or how to spin a real one up on the testing box within the test, expediently. 

I may get some time later this week or next week to push that forward, but if anyone amongst the `commons-vfs2` team has suggestions to point me in the right direction, I'm all ears!

**Comment by ottobackwards** [comment]
1.  There is no *commons-vfs team* as I have discovered myself.  It is tough to get reviews ( you can check my poor prs :( ).
2. I was going to look at the sshd / apache mina stuff to see if it had something, maybe look at the way *they* test it to see.  I would also look at apache nifi's sftp test stuff.  I have not had time yet, so if you want to, I would think about that.  If you can find another test suite/case that tests it, we can replicate that methodology.

**Pull request closed without merging**
